name: Status
form: $/acornassociated/calendar/models/status/fields.yaml
modelClass: AcornAssociated\Calendar\Models\EventStatus
defaultRedirect: acornassociated/calendar/eventstatuses
create:
    redirect: 'acornassociated/calendar/eventstatuses/update/:id'
    redirectClose: acornassociated/calendar/eventstatuses
update:
    redirect: acornassociated/calendar/eventstatuses
    redirectClose: acornassociated/calendar/eventstatuses
