title: Status
modelClass: AcornAssociated\Calendar\Models\EventStatus
list: $/acornassociated/calendar/models/status/columns.yaml
recordUrl: 'acornassociated/calendar/eventstatuses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
