plugin:
    name: acorn.calendar::lang.plugin.name
    description: 'Event calendar with repetition'
    author: 'Acorn'
    icon: wn-icon-calendar
    replaces: {  }
permissions:
    calendar_view:
        label: acorn.calendar::lang.permissions.view_the_calendar
        tab: acorn.calendar::lang.models.calendar.label
    change_the_past:
        label: acorn.calendar::lang.permissions.change_the_past
        tab: acorn.calendar::lang.models.calendar.label
    access_settings:
        label: acorn.calendar::lang.permissions.access_settings
        tab: acorn.calendar::lang.models.calendar.label
    # Create-system style permissions compatible
    acorn.calendar.calendar_create:
        label: acorn.calendar::lang.permissions.calendar_create
        tab: acorn.calendar::lang.models.calendar.label
    acorn.calendar.calendar_delete:
        label: acorn.calendar::lang.permissions.calendar_delete
        tab: acorn.calendar::lang.models.calendar.label
    acorn.calendar.calendar_print:
        label: acorn.calendar::lang.permissions.calendar_print
        tab: acorn.calendar::lang.models.calendar.label

    acorn.calendar.eventstatus_create:
        label: acorn.calendar::lang.permissions.eventstatus_create
        tab: acorn.calendar::lang.models.calendar.label
    acorn.calendar.eventstatus_delete:
        label: acorn.calendar::lang.permissions.eventstatus_delete
        tab: acorn.calendar::lang.models.calendar.label
    acorn.calendar.eventstatus_print:
        label: acorn.calendar::lang.permissions.eventstatus_print
        tab: acorn.calendar::lang.models.calendar.label
        
    acorn.calendar.eventtype_create:
        label: acorn.calendar::lang.permissions.eventtype_create
        tab: acorn.calendar::lang.models.calendar.label
    acorn.calendar.eventtype_delete:
        label: acorn.calendar::lang.permissions.eventtype_delete
        tab: acorn.calendar::lang.models.calendar.label
    acorn.calendar.eventtype_print:
        label: acorn.calendar::lang.permissions.eventtype_print
        tab: acorn.calendar::lang.models.calendar.label
navigation:
    calendar-menu-item:
        label: acorn.calendar::lang.plugin.name
        url: acorn/calendar/months
        icon: icon-calendar
        permissions:
            - calendar_view
        sideMenu:
            calendar-month-side-menu-item:
                label: acorn.calendar::lang.models.calendar.month
                url: acorn/calendar/months
                icon: icon-calendar
                permissions:
                    - calendar_view
            type-side-menu-item:
                label: acorn.calendar::lang.models.eventtype.label_plural
                url: acorn/calendar/eventtypes
                icon: icon-sliders
                permissions:
                    - calendar_view
            status-side-menu-item:
                label: acorn.calendar::lang.models.eventstatus.label_plural
                url: acorn/calendar/eventstatuses
                icon: icon-smile-o
                permissions:
                    - calendar_view
            calendars-side-menu-item:
                label: acorn.calendar::lang.models.calendar.label_plural
                url: acorn/calendar/calendars
                icon: icon-table
                permissions:
                    - calendar_view
