plugin:
    name: 'acorn.calendar::lang.plugin.name'
    description: 'Event calendar with repetition'
    author: 'Acorn'
    icon: wn-icon-calendar
    replaces: {  }
permissions:
    acorn.calendar.calendar_view:
        tab: Calendar
        label: 'View the Calendar'
    acorn.calendar.change_the_past:
        tab: Calendar
        label: 'Change the past'
    acorn.calendar.access_settings:
        tab: Calendar
        label: 'Access settings'
navigation:
    calendar-menu-item:
        label: 'acorn.calendar::lang.plugin.name'
        url: acorn/calendar/calendar
        icon: icon-calendar
        permissions:
            - calendar_view
        sideMenu:
            calendar-month-side-menu-item:
                label: Month
                url: acorn/calendar/calendar
                icon: icon-calendar
                permissions:
                    - calendar_view
            type-side-menu-item:
                label: 'Event Types'
                url: acorn/calendar/type
                icon: icon-sliders
                permissions:
                    - calendar_view
            status-side-menu-item:
                label: 'Event Statuses'
                url: acorn/calendar/status
                icon: icon-smile-o
                permissions:
                    - calendar_view
            calendars-side-menu-item:
                label: Calendars
                url: acorn/calendar/calendars
                icon: icon-table
                permissions:
                    - calendar_view
