name: Type
form: $/acorn/calendar/models/type/fields.yaml
modelClass: Acorn\Calendar\Models\Type
defaultRedirect: acorn/calendar/types
create:
    redirect: 'acorn/calendar/types/update/:id'
    redirectClose: acorn/calendar/types
update:
    redirect: acorn/calendar/types
    redirectClose: acorn/calendar/types
