name: Type
form: $/acornassociated/calendar/models/type/fields.yaml
modelClass: AcornAssociated\Calendar\Models\EventType
defaultRedirect: acornassociated/calendar/eventtypes
create:
    redirect: 'acornassociated/calendar/eventtypes/update/:id'
    redirectClose: acornassociated/calendar/eventtypes
update:
    redirect: acornassociated/calendar/eventtypes
    redirectClose: acornassociated/calendar/eventtypes
