name: Type
form: $/acorn/calendar/models/type/fields.yaml
modelClass: Acorn\Calendar\Models\EventType
defaultRedirect: acorn/calendar/eventtypes
create:
    redirect: 'acorn/calendar/eventtypes/update/:id'
    redirectClose: acorn/calendar/eventtypes
update:
    redirect: acorn/calendar/eventtypes
    redirectClose: acorn/calendar/eventtypes
