name: Events
modelClass: Acorn\Calendar\Models\Calendar
form: $/acorn/calendar/models/calendar/fields.yaml
defaultRedirect: acorn/calendar/listview
create:
    redirect: 'acorn/calendar/listview/update/:id'
    redirectClose: acorn/calendar/listview
update:
    redirect: acorn/calendar/listview
    redirectClose: acorn/calendar/listview
