name: Events
modelClass: AcornAssociated\Calendar\Models\Calendar
form: $/acornassociated/calendar/models/calendar/fields.yaml
defaultRedirect: acornassociated/calendar/listviews
create:
    redirect: 'acornassociated/calendar/listviews/update/:id'
    redirectClose: acornassociated/calendar/listviews
update:
    redirect: acornassociated/calendar/listviews
    redirectClose: acornassociated/calendar/listviews
