name: Month
form: $/acorn/calendar/models/calendar/fields.yaml
modelClass: Acorn\Calendar\Models\Calendar
defaultRedirect: acorn/calendar/month
create:
    redirect: 'acorn/calendar/month/update/:id'
    redirectClose: acorn/calendar/month
update:
    redirect: acorn/calendar/month
    redirectClose: acorn/calendar/month
