name: Status
form: $/acorn/calendar/models/status/fields.yaml
modelClass: Acorn\Calendar\Models\Status
defaultRedirect: acorn/calendar/status
create:
    redirect: 'acorn/calendar/status/update/:id'
    redirectClose: acorn/calendar/status
update:
    redirect: acorn/calendar/status
    redirectClose: acorn/calendar/status
