name: Event
form: $/acornassociated/calendar/models/eventpart/fields.yaml
modelClass: AcornAssociated\Calendar\Models\EventPart
defaultRedirect: acornassociated/calendar/months
create:
    redirect: 'acornassociated/calendar/months/update/:id'
    redirectClose: acornassociated/calendar/months
update:
    redirect: acornassociated/calendar/months
    redirectClose: acornassociated/calendar/months
