name: Calendars
form: $/acorn/calendar/models/calendar/fields.yaml
modelClass: Acorn\Calendar\Models\Calendar
defaultRedirect: acorn/calendar/calendars
create:
    redirect: 'acorn/calendar/calendars/update/:id'
    redirectClose: acorn/calendar/calendars
update:
    redirect: acorn/calendar/calendars
    redirectClose: acorn/calendar/calendars
