list: $/acornassociated/calendar/models/calendar/columns.yaml
modelClass: AcornAssociated\Calendar\Models\Calendar
title: Calendars
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acornassociated/calendar/calendars/update/:id'
