name: Status
form: $/acorn/calendar/models/status/fields.yaml
modelClass: Acorn\Calendar\Models\Status
defaultRedirect: acorn/calendar/statuses
create:
    redirect: 'acorn/calendar/statuses/update/:id'
    redirectClose: acorn/calendar/statuses
update:
    redirect: acorn/calendar/statuses
    redirectClose: acorn/calendar/statuses
