name: Event
modelClass: Acorn\Calendar\Models\EventPart
form: $/acorn/calendar/models/eventpart/fields.yaml
defaultRedirect: acorn/calendar/calendar
create:
    redirect: 'acorn/calendar/calendar/update/:id'
    redirectClose: acorn/calendar/calendar
update:
    redirect: acorn/calendar/calendar
    redirectClose: acorn/calendar/calendar
