name: Type
form: $/acorn/calendar/models/type/fields.yaml
modelClass: Acorn\Calendar\Models\Type
defaultRedirect: acorn/calendar/type
create:
    redirect: 'acorn/calendar/type/update/:id'
    redirectClose: acorn/calendar/type
update:
    redirect: acorn/calendar/type
    redirectClose: acorn/calendar/type
